### ISSUE TITLE
"'NoneType' object is not subscriptable" returned when starting the server

### ISSUE THREAD

**Issue by hfike** [arubdesu/Moscargo#1]
Starting the server using "python moscargo.py runwsgiserver port=5000 host=0.0.0.0", immediately receive the error "'NoneType' object is not subscriptable".
The server starts, however, it does not return the expected page.

**Comment by hfike** [comment]
Fixed here: https://github.com/macadmins/Moscargo/blob/master/moscargo/moscargo.py#L32-L52

**Comment by arubdesu** [comment]
Just in case archeologists are wondering what I had done wrong, 'get'ing non-present items from the one dictionary I was iterating over to shove it in another, while it does return something, (...none,) it doesn't result in a value that can be assigned to a key in the new dictionary. 😅 Closing
