### ISSUE TITLE
Not showing latest version

### ISSUE THREAD

**Issue by hfike** [arubdesu/Moscargo#3]
Repo currently has FileZilla 3.9.0.6 as well as the newer FileZilla 3.10.2. Moscargo is treating 3.9.0.6 as a newer version than 3.10.2.

Possible solution here: http://stackoverflow.com/questions/11887762/how-to-compare-version-style-strings

**Comment by hfike** [comment]
I have a fix, waiting for the PR to be submitted/merged for issue #1.

**Comment by arubdesu** [comment]
Should be addressed by most current push, let me whip up a tag and get all formal-like

**Comment by arubdesu** [comment]
Closing, please re-open if you notice any other tomfoolery - I think the fact I have Acrobat update .10 listed even though .9 is present should mean it's good. Thanks again for leading me by the nose, greatly appreciated.
